export const USE_CASES = {
  industrial: {
    icon: '⌬', label: 'Activo industrial', tag: 'Digital twin',
    description: 'Máquinas, herramientas, componentes y equipos de planta.',
    mode: 'image3d', category: 'industrial', profile: 'xreal', scale: 1.5, stlMm: 150,
    prompt: 'equipo industrial aislado, vista tres cuartos, geometría completa, iluminación uniforme, fondo blanco puro, sin personas ni texto',
    route: ['Referencia limpia', 'Malla 50K', 'GLB XR'],
  },
  vehicles: {
    icon: '◫', label: 'Vehículos', tag: 'Movilidad XR',
    description: 'Autos, SUV y utilitarios con carrocería y ruedas preservadas.',
    mode: 'image3d', category: 'vehicle', profile: 'xreal', scale: 4.5, stlMm: 180,
    prompt: 'vehículo completo aislado, vista tres cuartos, ruedas visibles, iluminación uniforme, fondo simple, sin personas',
    route: ['Referencia', 'Shape 192', 'PBR 1K'],
  },
  cargo: {
    icon: '▰', label: 'Vehículos de carga', tag: 'Logística',
    description: 'Pickups, furgones y equipos de reparto con volumen de carga separado.',
    mode: 'image3d', category: 'cargo_vehicle', profile: 'xreal', scale: 7, stlMm: 200,
    prompt: 'vehículo de carga completo, cabina y zona de carga visibles, vista tres cuartos, fondo simple, sin personas',
    route: ['Referencia', 'Ensamblaje', 'PBR 1K'],
  },
  trucks: {
    icon: '▣', label: 'Camiones', tag: 'Transporte pesado',
    description: 'Camiones rígidos, tractocamiones y remolques con ejes preservados.',
    mode: 'image3d', category: 'truck', profile: 'xreal', scale: 11, stlMm: 220,
    prompt: 'camión completo aislado, cabina, chasis, ejes y ruedas visibles, vista tres cuartos, fondo simple',
    route: ['Referencia', 'Partes', 'PBR 1K'],
  },
  cranes: {
    icon: '⌁', label: 'Grúas', tag: 'Izaje',
    description: 'Grúas móviles o industriales con pluma, cable, gancho y estabilizadores.',
    mode: 'image3d', category: 'crane', profile: 'xreal', scale: 10, stlMm: 220,
    prompt: 'grúa completa aislada, pluma, cable, gancho, cabina y estabilizadores visibles, fondo simple',
    route: ['Referencia', 'Partes finas', 'PBR 1K'],
  },
  electrical: {
    icon: 'ϟ', label: 'Instalaciones eléctricas', tag: 'Infraestructura',
    description: 'Tableros, transformadores, aisladores, canalizaciones y conjuntos eléctricos.',
    mode: 'image3d', category: 'electrical', profile: 'xreal', scale: 3, stlMm: 160,
    prompt: 'instalación eléctrica completa, tablero, aisladores y canalizaciones visibles, vista tres cuartos, iluminación uniforme',
    route: ['Escena técnica', 'Conexiones', 'PBR 1K'],
  },
  vegetation: {
    icon: '♣', label: 'Vegetación', tag: 'Entorno natural',
    description: 'Árboles, plantas y arbustos para escenas XR y visualización.',
    mode: 'image3d', category: 'vegetation', profile: 'xreal', scale: 4, stlMm: 180,
    prompt: 'árbol o planta completa aislada, tronco y follaje visibles, luz difusa, fondo simple',
    route: ['Silueta', 'Ramas', 'Follaje 1K'],
  },
  buildings: {
    icon: '▥', label: 'Edificios', tag: 'Arquitectura',
    description: 'Edificios completos, fachadas y volúmenes arquitectónicos.',
    mode: 'image3d', category: 'building', profile: 'xreal', scale: 18, stlMm: 240,
    prompt: 'edificio completo, fachada, cubierta, ventanas y accesos visibles, perspectiva tres cuartos, sin personas',
    route: ['Escena completa', 'Volumen', 'PBR 1K'],
  },
  tools: {
    icon: '⌕', label: 'Herramientas', tag: 'Mantenimiento',
    description: 'Herramientas manuales y eléctricas para capacitación y repuestos.',
    mode: 'image3d', category: 'tool', profile: 'xreal', scale: 0.6, stlMm: 140,
    prompt: 'herramienta completa aislada, mango, accionamiento y piezas visibles, vista tres cuartos, fondo blanco',
    route: ['Referencia', 'Forma técnica', 'PBR 1K'],
  },
  forklifts: {
    icon: '▦', label: 'Montacargas', tag: 'Logística interna',
    description: 'Grúas horquilla y equipos de manipulación de carga para planta y bodega.',
    mode: 'image3d', category: 'forklift', profile: 'xreal', scale: 2.5, stlMm: 190,
    prompt: 'montacargas completo aislado, mástil, uñas, cabina, ruedas y contrapeso visibles, vista tres cuartos, fondo simple',
    route: ['Referencia', 'Partes críticas', 'PBR 1K'],
  },
  excavators: {
    icon: '◩', label: 'Excavadoras', tag: 'Maquinaria pesada',
    description: 'Excavadoras y equipos de movimiento de tierra con articulaciones preservadas.',
    mode: 'image3d', category: 'excavator', profile: 'xreal', scale: 9, stlMm: 220,
    prompt: 'excavadora completa aislada, pluma, brazo, cucharón, cabina y orugas visibles, vista tres cuartos',
    route: ['Referencia', 'Articulaciones', 'PBR 1K'],
  },
  motorcycles: {
    icon: '◒', label: 'Motocicletas', tag: 'Movilidad ligera',
    description: 'Motocicletas y scooters con componentes finos, motor y ruedas preservados.',
    mode: 'image3d', category: 'motorcycle', profile: 'vrready', scale: 2.2, stlMm: 180,
    prompt: 'motocicleta completa aislada, dos ruedas, horquilla, motor, asiento y manillar visibles, vista tres cuartos',
    route: ['Referencia', 'VR 45K', 'PBR 1K'],
  },
  buses: {
    icon: '▭', label: 'Autobuses', tag: 'Transporte público',
    description: 'Buses urbanos, minibuses e interurbanos listos para escenas XR.',
    mode: 'image3d', category: 'bus', profile: 'vrready', scale: 12, stlMm: 230,
    prompt: 'autobús completo aislado, puertas, ventanas, ejes y ruedas visibles, vista tres cuartos, fondo simple',
    route: ['Referencia', 'VR 45K', 'PBR 1K'],
  },
  drones: {
    icon: '⌘', label: 'Drones', tag: 'Inspección aérea',
    description: 'Drones multirrotor para inspección, capacitación y simulación.',
    mode: 'image3d', category: 'drone', profile: 'lowpoly', scale: 0.8, stlMm: 150,
    prompt: 'drone multirrotor completo aislado, brazos, hélices, cámara y tren visibles, fondo blanco, sin movimiento',
    route: ['Referencia', 'Low Poly 15K', 'PBR 1K'],
  },
  boats: {
    icon: '⌇', label: 'Embarcaciones', tag: 'Operación marítima',
    description: 'Lanchas y embarcaciones para entrenamiento, puertos y visualización.',
    mode: 'image3d', category: 'boat', profile: 'vrready', scale: 8, stlMm: 220,
    prompt: 'embarcación completa aislada fuera del agua, casco, cubierta, cabina y propulsión visibles, vista tres cuartos',
    route: ['Referencia', 'VR 45K', 'PBR 1K'],
  },
  furniture: {
    icon: '▱', label: 'Mobiliario', tag: 'Interior XR',
    description: 'Muebles y equipamiento interior optimizados para escenas pobladas.',
    mode: 'image3d', category: 'furniture', profile: 'lowpoly', scale: 1.2, stlMm: 160,
    prompt: 'mueble completo aislado, patas, uniones y superficies visibles, vista tres cuartos, iluminación uniforme, fondo simple',
    route: ['Referencia', 'Low Poly 15K', 'PBR 1K'],
  },
  solar: {
    icon: '☼', label: 'Energía solar', tag: 'Infraestructura renovable',
    description: 'Paneles, inversores y soportes fotovoltaicos como activo o conjunto técnico.',
    mode: 'image3d', category: 'solar', profile: 'smart', scale: 6, stlMm: 210,
    prompt: 'instalación solar completa, paneles, marcos, soportes, cableado e inversor visibles, perspectiva tres cuartos',
    route: ['Escena técnica', 'Smart Apple M', 'PBR 1K'],
  },
  product: {
    icon: '▧', label: 'Producto comercial', tag: 'Catálogo 3D',
    description: 'Productos, packaging y objetos para web o comercio espacial.',
    mode: 'image', category: 'product', profile: 'mobile', scale: 0.35, stlMm: 100,
    prompt: 'fotografía de producto de un objeto completo, centrado, vista tres cuartos, iluminación de estudio suave, fondo blanco puro, sin sombras duras, sin texto',
    route: ['Crear imagen', 'Malla 20K', 'Móvil AR'],
  },
  organic: {
    icon: '◉', label: 'Animal o personaje', tag: 'Forma orgánica',
    description: 'Animales, mascotas, figuras y sujetos con anatomía orgánica.',
    mode: 'image', category: 'animal', profile: 'pcvr', scale: 1, stlMm: 120,
    prompt: 'sujeto de cuerpo entero, pose neutra de pie, vista tres cuartos, anatomía clara, objeto centrado, iluminación uniforme, fondo blanco puro, sin accesorios ni personas adicionales',
    route: ['Crear referencia', 'Hunyuan MLX', 'GLB 100K'],
  },
  mobilexr: {
    icon: '◌', label: 'Móvil y WebXR', tag: 'Rendimiento',
    description: 'Activos ligeros para navegador, tablet y realidad aumentada móvil.',
    mode: 'image3d', category: 'product', profile: 'mobile', scale: 1, stlMm: 100,
    prompt: 'objeto simple y completo, silueta limpia, pocos detalles pequeños, fondo blanco puro',
    route: ['Referencia', 'Malla 20K', 'Textura 1K'],
  },
  print3d: {
    icon: '△', label: 'Impresión 3D', tag: 'STL sólido',
    description: 'Piezas paramétricas, soportes y prototipos imprimibles.',
    mode: 'stl', category: 'industrial', profile: 'lowpoly', scale: 0.12, stlMm: 120,
    prompt: 'pieza funcional imprimible, sólida y watertight, base plana, paredes de mínimo 2 mm, dimensiones aproximadas 120 mm',
    route: ['Texto técnico', 'Sólido watertight', 'STL'],
  },
  master: {
    icon: '◆', label: 'Activo maestro', tag: 'Máxima calidad',
    description: 'Modelo base de alta fidelidad para optimizar después en distintas salidas.',
    mode: 'image3d', category: 'custom', profile: 'maxquality', scale: 1, stlMm: 150,
    prompt: 'objeto completo de alta fidelidad, detalles visibles, iluminación de estudio uniforme, vista tres cuartos, fondo blanco puro',
    route: ['Referencia 2K', 'Malla 200K', 'GLB maestro'],
  },
};
